export const UserStorageConst = {
  UserName: 'USER_NAME',
  Password: 'PASSWORD',
};

export const LoginConst = {
  ACTION_LOGIN: 'LOGIN',
  ACTION_LOGOFF: 'LOGOFF',
  LOGIN_SUCESSFUL: 'LOGIN_SUCESSFUL',
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_LOADED: 'LOGIN_LOADED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOFF: 'LOGOFF',
  USER_INFO_LOGIN: 'USER_INFO_LOGIN',
};

export const ProfileConst = {
  GET_USER_SUMMARY: 'GET_USER_SUMMARY',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_PERMISSIONS: 'GET_USER_PERMISSIONS',
  GET_USER_ALL: 'GET_USER_ALL',
  USER_LOADING: 'USER_LOADING',
  USER_ERROR: 'USER_ERROR',
};
